[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Contigo"
authors = [{name = "Manexware", email = "info@manexware.com"}]
dynamic = ["version", "description"]
